[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "locust-csv-to-junit-xml"
version = "1"
dependencies = []

[project.optional-dependencies]
dev = [
  "flask===2.3.2",
  "junitparser===2.1.1",
  "locust===2.4.3",
  "nose2===0.10.0",
]
